version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: your_password
      MYSQL_DB: your_database

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_USER: your_user
      MYSQL_DATABASE: your_database
      MYSQL_PASSWORD: your_database
    volumes:
      - ./my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:

